server:
  port: 9162

# ajpPort
tomcat:
  ajp:
    protocol: AJP/1.3
    enabled: true
    remoteauthentication: false
    port: 9091

# InternalResourceViewResolver
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@//localhost:1521/xe
    username: secondacc75
    password: secondacc75
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        #        show-sql: true
        format_sql: true
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: seoulit50@gmail.com
    password: "!admin8282"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
        auth: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*SqlMap.xml
  type-aliases-package: kr.co.seoulit.account
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true

# logging
logging:
  level:
    org.hibernate: info
    com.azurealstn.codespringweb.mapper: debug
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
